### ISSUE TITLE
[SB8]: expandable search input is not clickable

### ISSUE THREAD

**Issue by Jura** [undp/design-system#1376]
https://develop.design-system.pages.dev/?path=/story/components-forms-search-expand--search-expand-story

it works when injected in Docs section: https://develop.design-system.pages.dev/?path=/docs/components-forms-search-expand--docs

**Comment by CalebLuster** [comment]
This was also an issue in the current design system. Whichever instance was clicked first (docs or story) would expand and then the other wouldn't. 

Fixed by adding a useRef hook and adjusting the jQuery so it doesn't get all instances of  `expand-search` and is narrowed down to the local instance.

**Comment by Jura** [comment]
Confirmed
