### ISSUE TITLE
Implement updated Our Expertise section

### ISSUE THREAD

**Issue by Jura** [undp/design-system#904]
Figma: https://www.figma.com/file/U6HtgMaCzkhXgTpKNz2Ial/UNDP-Global-Site?node-id=153%3A18293

**Comment by Jura** [comment]
@theadamparker , over to you for comments: https://develop.design-system.pages.dev/?path=/story/templates-global-homepage--global-homepage . 
Implementation notes:
- I haven't added any support for non-English languages so far as that section is only affects our global site and we do not plan to allow it anywhere else.
- will need to test it with real content as uneven distribution of content in various slides may throw off the layout

**Comment by Jura** [comment]
@theadamparker if there are any tweaks we need to add to the section - can you mention them here? Otherwise we can resolve this ticket as it has been already released in 1.0.5

**Comment by Jura** [comment]
@theadamparker , where do we stand with that?

**Comment by theadamparker** [comment]
Looks very good overall @Jura. A few details: 

### To discuss

- The cursor arrow wasn't part of the original design, but it's a nice touch. However it seems redundant with the buttons. Should we show cursor for mouse inputs and buttons for touch inputs? Buttons also provide a visual clue that this is a carousel. 
- Can we use the actual copy and photos rather than placeholders? I can provide the details.

###  Issues

- Buttons (chevrons in circles) aren't using a hover state. 
- Tabs (Signature Solutions and Enablers) should… 
  - Be clickable, with a click leading to the first item of each
  - Follow the same treatment (e.g. hover state) as the [tabs UI component](https://design.undp.org/?path=/story/components-ui-components-tabs--tabs).
  - Paragraph text within the slider should be `$gray-600`. Currently it is black.

**Comment by Jura** [comment]
Copy and images: https://docs.google.com/document/d/1A_WmsR9_tcQh-pyhTZgM1-46SoIy5umc9YEilGeKF8U/edit

**Comment by Jura** [comment]
@theadamparker , changes are deployed here: https://develop.design-system.pages.dev/, let me know if good enough for release

**Comment by theadamparker** [comment]
Looking really good @Jura . A few final adjustments: 

- Learn more CTA should use “space” not “expanding arrow”
- Carousel paragraph text should be `gray-600` (currently black)
- Width of the tabs shouldn’t fill its entire container. It should hug the width of its contents.
![Screen Shot 2022-11-04 at 1 46 48 PM](https://user-images.githubusercontent.com/2205158/200041992-ecedaec3-89db-4721-a2fe-c8b25ed90711.png)

- Currently the tab titles (e.g. Directions of change) wrap to keep all tabs on one line. The original design was to keep tab titles on one line, and wrap tabs as needed. I’m open to keeping it all tabs on a single row, however now the full width of the tab component interferes with the position indicator (1/6) at some common sizes (approximately 1240px wide). 
![Screen Shot 2022-11-04 at 1 47 35 PM](https://user-images.githubusercontent.com/2205158/200042138-db1feb13-3ef8-4615-a270-5832f1348521.png)

**Comment by theadamparker** [comment]
Looks good with the recent fixes.
