### ISSUE TITLE
Scrollbars are not styled properly in Firefox

### ISSUE THREAD

**Issue by Jura** [undp/design-system#907]
https://design.undp.org/?path=/story/utilities-scrollbars--scrollbars
Firefox rendering: 
![image](https://user-images.githubusercontent.com/417604/160243584-59c9d21a-4b8a-41ca-8496-bfb709567cb6.png)

Correct rendering: 
![image](https://user-images.githubusercontent.com/417604/160243631-da0d81e4-763b-43b2-be5c-30f2263f2276.png)

**Comment by paboden** [comment]
Hi @Jura, Looks like firefox has some really restrictive rules about the scrollbar styling. I'm not sure If I can get it to match. Here are some screenshots of the best I've been able to do so far with the limited style control that firefox has.

This one I can set a border just to the side of the bar.
![Screen Shot 2023-02-09 at 12 12 19 PM](https://user-images.githubusercontent.com/3878820/217926860-6ba51a08-fc53-4e2c-b7ea-814d65748ab8.png)

This one is without the border. Firefox doesn't allow effecting the round ends of the scrollbar element.
![Screen Shot 2023-02-09 at 12 12 45 PM](https://user-images.githubusercontent.com/3878820/217926863-de4d95b8-fbd7-428a-98c3-8cc81d5007d9.png)

Here is an example of it with the download modal.
![Screen Shot 2023-02-09 at 12 12 54 PM](https://user-images.githubusercontent.com/3878820/217926864-dd62aa64-fec1-4f53-a803-2eca4b779392.png)

How should we approach this? 
- Use one of the 2 versions for now until firefox allows for more scrollbar style control?
- Stick with default scrollbars?
- keep working on it and look for a plugin/library that can allow us to control it on firefox?

Cheers
Phil

**Comment by paboden** [comment]
Hi @Jura 
I think I was able to figure out a box-shadow css hack for firefox scrollbars. For the trick, there is a white edge that has to go along with the black thin bar, to create the illusion of a thin black bard down the scroll. Scrollbars on any non-white backgrounds may look off because of this css hack. The good news is this will just be for firefox, and it doesn't seem like scrollbars on colored/dark backgrounds appear that often.

Let me know what you think.

**Comment by Jura** [comment]
@mrelevo , please verify

**Comment by mrelevo** [comment]
verified in DEv
